### ISSUE TITLE
Source Editing Area and Source Dialog are both loaded in Composer and block form modals

### ISSUE THREAD

**Issue by MrKarlDilkington** [ExchangeCore/Concrete5-CKEditor#23]
It appears that outputPageComposerEditor(), outputBlockEditModeEditor(), and outputStandardEditor() are loading both source code plugins.

Is it possible to load the Source Dialog plugin for outputPageInlineEditor() only?

**Examples:**

_Composer_

![double_source-composer](https://cloud.githubusercontent.com/assets/10898145/10781661/74624830-7d1f-11e5-8dec-b685427146fd.png)

_Block Form Modal_

![double_source-form_modal](https://cloud.githubusercontent.com/assets/10898145/10781663/79646aca-7d1f-11e5-9005-ec1e3ca48bc8.png)

**Comment by joe-meyer** [comment]
Ya I think the right answer is a more robust plugin management system. I'd like to avoid using the `editor.config.removePlugins` setting if we can avoid it since this seems kind of hacky and I imagine that as more plugins are developed there will be a need to tell the editor "The plugin works for inline only" or something of the like. 

We do this with concrete5inline, but the bad part is we load this file on everything and just return out if we detect it's not the proper type of editor, meaning we're loading extra assets that don't get used.
