### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by pvernaglia** [ExchangeCore/Concrete5-CKEditor#27]
Hey guys, this is awesome!  Thanks so much for doing this, I'm really looking forward to this as an add on.  I installed it today and it works very well, my only comments are on adding images.  I think it the responsive world it is better to not embed the height and width tags on images and it would be nice in the Image add box to be able to add margins and maybe a class to the image.

Great job,
Peter

**Comment by joe-meyer** [comment]
@pvernaglia thanks for the feedback. 

First off, I think our goal was to not set the image width/height by default. This is the default behavior when you pick something from the file manager. If you do pick something from an external source, then it will populate the width and height by default, but this can be adjusted or removed (this is the default for the ckeditor image stuff so I'm hesitant to change that and maintain it). If you use the "Browse Server" button to pick your images then everything should work as you describe there.

With regard to the Class adding to the image..... We have a little bit of a trade off here... If you didn't noticed, we have a plugin called "Enhanced Image" turned on as a default. We did this because the User Interface felt simpler, it allowed for captions to be easily added, and it allowed for an easy way for users to align their images; additionally you can still edit the source code to add other things like classes. However, if you disable this add in the dashboard "Rich Text Editor" page, you will see that when you edit an image you gain access to a slew of more technical features. but lose the "Simpler" UI. You should however, be aware that the [concrete5 link abstraction](https://github.com/concrete5/concrete5/blob/develop/web/concrete/src/Editor/LinkAbstractor.php#L124-L129), has some code, where if it detects that you are using the `style=""` attribute in your image code, it will not automatically use the `<picture>` object, so you may either want to look into a core PR to fix this, or just avoid using the `style` attribute on your image objects.

Image with `style`:
![image](https://cloud.githubusercontent.com/assets/1292766/11170320/8e792b5c-8b9e-11e5-840d-83ffa0b28402.png)

Image without `style`:
![image](https://cloud.githubusercontent.com/assets/1292766/11170323/965ee10e-8b9e-11e5-845a-931f4c2976e6.png)

Does this help clarify?

**Comment by pvernaglia** [comment]
I was looking at the source in CKEdit and saw the height and width on the image before I saved the block, I see now, once saved it is no longer there.

I didn't know about the Enhanced Image option, I found it in with all the Redactor settings.  You might think about separating them out with their own heading for CKEdit or having a CkEdit dashboard page?

I see what your saying about the picture tag, if you select left right or center alignment the tag is no longer present. I do think the margin on the image is a little bit of a problem, with Enhanced Image off I can add horiz or vertical spacing but it puts it on both sides or both top and bottom of the image, the same way Tiny did.  I always found that an annoyance, when I have the text wrapping right of the image I really only want the margin on the right and bottom of the image.  

It's not a real big deal, but for the client who needs it simple it adds some extra explaining and extra mistakes. Some way to add margins or have a class added when alignment is used so images could be styled globally would be a nice option.

As always, I appreciate everything you do Joe.

**Comment by joe-meyer** [comment]
Right now I'm trying to avoid adding custom plugins that we'll have to maintain ourselves to the repository because it's going to make upgrading to the newer versions of CKEditor as they roll out more difficult if we have to update more code to do it.

@MrKarlDilkington do you know of any built in plugins that might accomplish the same things or have any suggestions? I think if it's all about spacing, you could use the div container manager to wrap a div around the image and set a style on that... it seems kind of hacky but it would probably work. 

As far as the dashboard page... It is meant to be a generic page, we recently had some pull requests in so that it doesn't say "Redactor" on that page anymore. That said I do think at some point we're going to need to build additional dashboard pages to manage all the additional functionality CKEditor provides and at that point we'll probably abandon that system page but it's not an immediate need right now. (We also documented this page in our documentation https://docs.exchangecore.com/community_ckeditor/develop/ :wink: )

**Comment by MrKarlDilkington** [comment]
@pvernaglia 

What you are looking to do can be done with "widget styles". In CKEditor there are inline, block, object, and widget styles. These different types of styles can be used to anticipate your client design needs in advance. You could offer them a variety of predefined image widget styles where margin is already handled. Examples could be "Image Caption Right", "Image Left", "Image Right", etc. Each style can have CSS properties and values and HTML attributes like class.

Here is a screen recording of a widget style being applied to an image:
http://www.screencast.com/t/67LejkCmmv8O

Here are examples of styles:
https://github.com/ExchangeCore/Concrete5-CKEditor/blob/develop/vendor/ckeditor/styles.js

Widget Styles
http://ckeditor.com/tmp/4.4.0/widget-styles.html

General Styles Overview
http://docs.ckeditor.com/#!/guide/dev_styles

**Comment by MrKarlDilkington** [comment]
After thinking about it, I believe this could be better handled with regular CSS. But there would be nothing stopping you from making a widget style.

Example:

**1 - image floated right**

![1](https://cloud.githubusercontent.com/assets/10898145/11175390/b4094c7e-8bff-11e5-9162-66060cf10262.png)

**2 - after adding selector that targets images with inline style float right and that are children of picture**

```
picture img[style*="float:right"]{
    margin: 20px 0px 20px 20px;
}
```

![3](https://cloud.githubusercontent.com/assets/10898145/11175395/bec8cc5c-8bff-11e5-9eb1-2ecf10e5fdf4.png)

You could predefine margins in your theme CSS for left/right floated images.

**Comment by MrKarlDilkington** [comment]
After thinking about it and looking into it more, I found another (better) approach "Images Aligned with Classes".

"CKEditor 4.4 introduces the new config.image2_alignClasses configuration option, which, along with the config.image2_captionedClass setting, gives developers more control over the widgets and makes the styling process much easier. For example, the following configuration:

```
CKEDITOR.replace( 'editor1', {
    extraPlugins: 'image2',
    image2_alignClasses: [ 'image-left', 'image-center', 'image-right' ],
    image2_captionedClass: 'image-captioned',
} );
```

will produce class-driven, stylable markup (e.g. class="image-right" instead of style="float:right"), avoiding inflexible and non-semantic inline CSS:

```
<figure class="image-captioned image-right">
    <img alt="Image" src="example.png" />
    <figcaption>Caption</figcaption>
</figure>
```

"
http://ckeditor.com/tmp/4.4.0/widget-styles.html

This appears to create element classes specifically for the Enhanced Image plugin. With the classes you can avoid inline CSS. The would require themes to have styling rules for image-left, image-center, image-right, and image-captioned.

I could make a list of default styles that people could use to get started using CKEditor (as part of the installation documentation). With the explanation that these styles are just a boilerplate that can be customized.

**Comment by pvernaglia** [comment]
I think both examples in your last two messages are a fine solution for people like you an me, but  the guy with a purchased a theme who adds this add on to their site might be in over their heads.  It surprises me CKEdit, Tiny, Redactor, etc hasn't tackled this already.  You are always going to want some spacing around images when text is being wrapped around them.  I think it's worth finding the best solution for this.

Also, should the img-responsive class be on an image as well?   I think a majority of sites are being done in Bootstrap these days.

**Comment by MrKarlDilkington** [comment]
I understand your position.

Because the default image function includes margin controls, then perhaps this should be made the default and Enhanced Image would be optional. People would be using Enhanced Image for the extra functionality of easy image resizing and the image caption. To use the image caption, it requires CSS to be added to a theme, so requiring float margin CSS at the same time is not unreasonable. In the documentation there could be a note that caption and floats used in the Enhanced Image plugin require adding CSS to the theme. Sample CSS would be provided for users to use.

Things will be different if CKEditor 5 is used in the next version of concrete5. This would allow for establishing best practices for theme makers in how they write styles for it.

I like the idea of adding a default class to the image to use as a styling hook. Whether it is img-responsive or something else.

**Comment by joe-meyer** [comment]
So.. I'm definitely opposed to adding an img-responsive class to images by default. This seems like we're overstepping our bounds a lot for an editor plugin and moving into a "Bootstrap editor" plugin. Also, there's no real way to be certain people want a responsive image, so I'm inclined to pass on that one. I think there's been some talk of abstracting out the link abstractor stuff in the concrete5 core, which might allow for the picture / link things to obtain a default class from a theme or package and I think that's probably more appropriate than us trying to inject defaults from a content editor perspective. @ChrisHougard (or anyone else watching) Do you have any thoughts on a default styling hook here? If we added something I'd think we'd want it to be something pretty unique such as `content-editor-image` or something like that so that if other editors wanted to leverage it they could, but it's still not going to inherit things like img-responsive.

@MrKarlDilkington I think you should move the version 5 stuff to a new issue. I'm thinking that at some point we may want to support multiple versions of CKEditor and a version picker which would then allow only plugins that match that version to be used.

**Comment by MrKarlDilkington** [comment]
@joe-meyer 

I like "content-editor-image". It is unique enough for selector targeting, but generic enough that it isn't bound to a specific editor.

**Comment by pvernaglia** [comment]
I don't think img-responsive oversteps bounds, if it's not a bootstrap theme it's ignored, either way no big deal.  

I think the basic problem boils down that we can all come up with ways to style an image in this content editor, but our mom's can't, well my mom anyways! 

In my opinion, if someone places an image with text to the left or right there should be some spacing by default so it looks nice. If they want more than the default then they need to be able to deal with CSS.

**Comment by joe-meyer** [comment]
@pvernaglia I think at this point my biggest problem with implementing something custom to accommodate this is having to support it. I'd really love to be able to roll up to CKEditor version 5 within a short period after it comes out and not have any loss of functionality. 

I definitely agree that there's a bit of a hole in terms of image placement when it comes to concrete5 and image editing (although layouts do go quite a ways). I'm just not sure that I want to be the keeper of such functionality. That said.... if someone wanted to make a PR to implement it, I don't think I'd be opposed and it would probably be much easier to maintain after that.

**Comment by joe-meyer** [comment]
So... While I was perusing for a way to implement the concrete5 magic stuff I noticed there was a [CKEditor Responsive Images](http://ckeditor.com/addon/imageresponsive) plugin which looked like an enhancement to the enhanced images plugin. I haven't bothered to try it out yet but perhaps that plugin would achieve what you were looking for.

**Comment by joe-meyer** [comment]
@MrKarlDilkington I think we can close this out via #28 right?

**Comment by MrKarlDilkington** [comment]
@joe-meyer 

Yes, with your LinkAbstractor PR accepted, this is resolved.
