### ISSUE TITLE
Autogrow plugin does not apply autoGrow_minHeight or autoGrow_minHeight

### ISSUE THREAD

**Issue by MrKarlDilkington** [ExchangeCore/Concrete5-CKEditor#42]
These settings are ignored by the plugin.

![block_needs_min_height](https://cloud.githubusercontent.com/assets/10898145/12069544/75e9d2cc-b005-11e5-9d50-0eaadf9ca6b3.png)

![composer_needs_min_height](https://cloud.githubusercontent.com/assets/10898145/12069545/79dd29ce-b005-11e5-9540-2c23cbfaa5a6.png)

**Comment by joe-meyer** [comment]
Turns out this is because we use the `divarea` plugin. Disabling this makes that behave properly but we obviously lose that plugins functionality then. 

https://dev.ckeditor.com/ticket/9351 provides some more incite on the situation but for now I'm thinking this isn't a critical bug especially since the div area still grows automatically. PR would be welcome if someone wants to implement a workaround.

**Comment by joe-meyer** [comment]
Calling this good enough via #44 and #45. Thanks @MrKarlDilkington
