### ISSUE TITLE
Editing blocks with CKEditor wysiwyg fields and image fields

### ISSUE THREAD

**Issue by tduncandesign** [ExchangeCore/Concrete5-CKEditor#47]
Forgive me if I put this in the wrong place, I'm not familiar with Github practices.

I'm running the CKEditor on a 5.7.5.6 install, and using the Block Designer Pro add on. The issue is if I have a wysiwyg field and and image field in a block, CK Editor is loaded, and then I can't clear and choose new image (or files) upon subsequent editing of the block. If I un-install CKEditor the editing behavior of the block is as expected.

The discussion is over here: https://www.concrete5.org/marketplace/addons/block-designer-pro/support/repeating-file-picker-fields/#804352

The fix Ramon put forward to force Redactor in these blocks works. I just thought you guys might like to know about this. 

Thanks for all your efforts on CKEditor!

**Comment by joe-meyer** [comment]
@tduncandesign I took a look at the support issue you had. What Ramon suggested would be what I consider a "hack" because it avoids using the editor interface. I'm not familiar with the block-designer-pro but I do know that when you try to initialize the editors via javascript it causes problems because you end up with duplicate ID's and you can't re-run all the PHP logic tied to the existing editor, this is currently something the core editing interface is lacking and even in some of the core blocks it is kind of hacked together in the way Ramon did. 

I'm closing this out because it's not an issue with ckeditor, but rather an issue with the implementation of the plugin (and admittedly no "easy" way I know of to get around it without modifying the core in some way). Since CKEditor is going to be the core editor in concrete version 8,  I suspect that something might be done or examples might be found there on how Ramon can better work around the problem without hard coding redactor.
