### ISSUE TITLE
Need to remove the ckeditor from upload_complete page or enable it in to a package

### ISSUE THREAD

**Issue by tkart38** [ExchangeCore/Concrete5-CKEditor#58]
hi
i've a site with this two package installed ckeditor and problog.
All is fine but the ckeditor is loaded on the upload file dialog from the problog add_blog procedure and conflict with the redactor.js.
Where i can' disable the load of ckeditor on this dialog ? or how i can enable the ckeditor on the pro blog package?
any ideas?
thanks

update: i've found that the ckeditor are loaded because i've a textarea file attribute.

**Comment by joe-meyer** [comment]
I can't confirm since I don't have problog but the issue is most likely that the problog developer did not properly use concrete5's editor abstraction layers and therefor they have hard coded redactor in a place where ckeditor should be used. If you install CKEditor the intention is that all editor areas will use it. This is the case with concrete5 version 8 as well.

**Comment by tkart38** [comment]
hi thanks for reply.
then if i need to load the ckeditor on a package i'v to do nothing? onlie disable redactor if is present?
or i need to "include" the ckeditor.js on package single page
how can i initialize it? 
or how can i add the editor abstraction layer to my new package?
thanks in advaces
bye

**Comment by tkart38** [comment]
i've solved all my problem doing this on the package:

$editor = Core::make('editor');
echo $editor->outputStandardEditor('blogBody', $notes);

this load automaticaly the ckeditor as expected!
thanks
